### ISSUE TITLE
EPPlus.dll throws an error when there is a space in the TableName

### ISSUE THREAD

**Issue by DarkLite1** [DHMechatronicAG/EPPlus#1]
In the previous version of the EPPlus.dll it was possible to use spaces for TableName, at the moment this is no longer the case and his handled as an Exception.

See the last clause in the following code:

        private void ValidateTableName(string Name)
        {
            if (string.IsNullOrEmpty(Name))
            {
                throw new ArgumentException("Tablename is null or empty");
            }

            char firstLetterOfName = Name[0];
            if (Char.IsLetter(firstLetterOfName) == false && firstLetterOfName != '_' && firstLetterOfName != '\\')
            {
                throw new ArgumentException("Tablename start with invalid character");
            }

            if (Name.Contains(" "))
            {
                throw new ArgumentException("Tablename has spaces");
            }

        }

Is there a specific reason why this is now treated as an Exception? 

See [Export-Excel](https://github.com/dfinke/ImportExcel/issues/165) for related info.

**Comment by OomJan** [comment]
This change was made in the main repository on 01.09.2015. I'm not sure what the reasoning behind this is. You may want to redirect your question to the main repository on Codeplex or try removing that check yourself and see if there are any consequences.

Reference:
http://epplus.codeplex.com/SourceControl/changeset/f7667fe07275

**Comment by DarkLite1** [comment]
Thanks for the feedback. I've only seen later that you forked the project so I opened indeed another [issue ](http://epplus.codeplex.com/workitem/15588) at the author's page. I will close this one then.
